config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
    resources :articles
  root 'articles#index'

  resources :articles do
    resources :comments
  end
  get '/categories/:category_handle/posts', to: 'articles#index', as: :category_articles
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 belongs_to :category
   has_many :comments, dependent: :destroy
belongs_to :user
   scope :ordered, -> { order(id: :desc) }
   scope :with_categories, -> { includes(:category) }


  validates :title, presence: true,
                   length: { minimum: 5 }
end

app/models/category.rb
class Category < ApplicationRecord
has_many :articles, dependent: :nullify

def self.find_by_handle!(handle)
    find_by(handle: handle) || 
    raise(ActiveRecord::RecordNotFound)
end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true,
                   length: { minimum: 5 }
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :articles
         has_many :comments

  def username()
    return self.email.split('@')[0]
  end
    



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 

def index
  @articles = Article.all
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

  def index

    if params[:category_handle]
      @category = Category.find_by_handle(params[:category_handle])
      @articles = @category.articles.ordered.with_categories
    end


    @articles ||= Article.ordered.with_categories

  end

  def show
      @article = Article.find(params[:id])
    end



  def new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
      @article = current_user.articles.build(article_params)

      if @article.save
        redirect_to @article
      else
        render 'new'
      end
   end

   def update
  @article = Article.find(params[:id])

  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
end

private
 def article_params
   params.require(:article).permit(:title, :text, :category_id)
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController




  def create
  @article = Article.find(params[:article_id])
  @comment = @article.comments.create(comment_params)
  @comment.user_id = current_user.id
  @comment.commenter = current_user.username
  @comment.save!
  redirect_to article_path(@article)
end

def destroy
  @article = Article.find(params[:article_id])
  @comment = @article.comments.find(params[:id])
  @comment.destroy
  redirect_to article_path(@article)
end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class = 'form-group postInputForm'>
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'form-control' %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, class: 'form-control'  %>
  </p>

  <p>
    <%= form.label :category_id %><br>
    <%= form.select :category_id, Category.all.map {|c| [c.name, c.id]}, class: 'form-control'  %>
  </p>

  <p>
    <%= form.submit %>
  </p>



<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>
<%= @category&.name || "All "%> posts
</h1>



<div class = "posts">
  <% if @category%>
  <%= link_to "All posts", articles_path%>
  <% end%>

  <%= link_to 'New article', new_article_path %>
<table>
  <tr>
  <th>Category</th>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>

    <tr class = 'postsTable'>

        <td><%= link_to article.category.name, category_articles_path(category_handle: article.category.handle)  %></td>
      <td><%= article.title %></td>
      <%if article.text.length >=150 %>
      <td><%= article.text[0...150]...%></td>
      <% else %>
      <td><%= article.text %></td>
      <% end%>
      <td><%= article.user.username %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
        <%if current_user %>
      <%if article.user_id == current_user.id%>
       <td><%= link_to 'Edit', edit_article_path(article) %></td>
       <td><%= link_to 'Destroy', article_path(article),
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
             <% end %>
             <% end %>
   </tr>

  <% end %>
</table>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class = postInputForm>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
<strong>Author:</strong>
<%= @article.user.username %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
</div>
<h2>Comments</h2>
<%= render @article.comments %>


<%if !current_user%>
<h4>Login to add a comment</h4>
<% else %>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 <%if @article.user_id == current_user.id%>
 <%= link_to 'Edit', edit_article_path(@article) %> |

<% end %>
<% end %>


<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class = 'postInputForm'>
<p>
  <strong>Author:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<%if current_user%>
<%if comment.user_id == current_user.id%>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
<%= hidden_field_tag(:commenter, current_user.username()) %>
  <p>
    <%= form.label  :Message %><br>
    <%= form.text_area :body %>
  </p>
  <p>
     <%= form.submit%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <nav class="navbar navbar-light bg-light">
<h4>Ruby entrance blog</h4>
    <div class = 'navbarCategories'>
      <% Category.all.each do |c| %>
      <%= link_to c.name, category_articles_path(category_handle: c.handle) %>
<%end %>
      </div>
      <div class = 'navbarСontent'>
      <% if current_user %>
       <span>Hi, <%= current_user.username%>!</span>
       <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
      <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
      <% end%>


</div>
</nav>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>